# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

pool:
  vmImage: 'vs2017-win2016'

trigger:
  batch: true
  branches:
    include:
    - master
    - develop

steps:
  - powershell: |
      .\Build\build.ps1 -ResolveDependency -TaskList 'CombineFunctionsAndStage'
    displayName: 'Compile'

  - powershell: |
      .\Build\build.ps1 -TaskList 'Analyze'
    displayName: 'Analyze'

  - powershell: |
      .\Build\build.ps1 -TaskList 'Test'
    displayName: 'Test'

  - powershell: |
      .\Build\build.ps1 -TaskList 'UpdateDocumentation'
    displayName: 'Update Documentation'

  - powershell: |
      .\Build\build.ps1 -TaskList 'CreateBuildArtifact'
    displayName: 'CreateBuildArtifact'

  - task: PublishTestResults@2
    displayName: 'Publish Unit Tests'
    inputs:
      testRunner: 'NUnit'
      searchFolder: 'Artifacts'
      testRunTitle: 'UnitTests'
    condition: always()

  - task: PublishBuildArtifacts@1
    displayName: 'Publish Artifact: Module'
    inputs:
      PathtoPublish: Artifacts
      ArtifactName: Artifacts
    condition: always()
