# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

pool:
  vmImage: 'vs2017-win2016'

trigger:
  batch: true
  branches:
    include:
    - master
    - develop

steps:
  - task: PowerShell@1
    displayName: Run Unit Tests
    inputs:
      scriptType: filePath
      scriptName: "Build/build.ps1"
      arguments: -Task 'Test'

  - task: PublishTestResults@2
    inputs:
      testRunner: 'NUnit'
      testResultsFiles: '**UnitTestResults.xml'
      testRunTitle: 'UnitTests'
    condition: always()
