# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

pool:
  vmImage: 'vs2017-win2016'

trigger:
  batch: true
  branches:
    include:
    - master
    - develop

steps:
  - powershell: |
      .\Build\build.ps1 -ResolveDependency -TaskList 'Release'
    displayName: 'Run Unit Tests'

  - task: PublishTestResults@2
    displayName: 'Publish Unit Tests'
    inputs:
      testRunner: 'NUnit'
      testResultsFiles: '**UnitTestResults.xml'
      testRunTitle: 'UnitTests'
    condition: always()

  - task: PublishBuildArtifacts@1
    displayName: 'Publish Artifact: Module'
    inputs:
      PathtoPublish: Artifacts
      ArtifactName: Artifacts
    condition: always()
